version: "3.7"

services:

  project-prism:
    container_name: project-prism
    image: stoplight/prism
    volumes:
      - ./prism/marmitakoo.yaml:/marmitakoo.yaml
    command: >
      mock -p 4010 -h 0.0.0.0 -d /marmitakoo.yaml
    networks:
      - project-network

  #PHP Service
  project-php:
    build:
      context: docker/php-fpm
      args:
        user: nico
        uid: 1000
    container_name: project-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - project-network
    external_links:
      - project-prism:prestashop.marmitakoo.test

  #Nginx Service
  project-nginx:
    image: nginx:alpine
    container_name: project-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/public
      - ./var/log:/var/log/nginx
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - project-network

#Docker Networks
networks:
  project-network:
    driver: bridge

